<a href="https://colab.research.google.com/github/codesamskaaraH/ML_dev/blob/master/EQ_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

In [17]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
X_train_df = pd.read_csv("/content/drive/My Drive/DrivenData/EQ/EQ_Train_Values.csv", index_col= 'building_id')
Y_train_df = pd.read_csv("/content/drive/My Drive/DrivenData/EQ/EQ_Train_Labels.csv", index_col= 'building_id')
#index_col is used as row label for this data set as the each building is uniquely identified by this id, also
#submission CSV requires this id

In [19]:
#various prints to check the data set
#print(X_train_df.describe())
X_train_df.head(100)
# shape of df is = 260601, 38
print(X_train_df.shape)
#X_train_df.describe()
#X_train_df.dtypes
#X_train_df.info()
print(Y_train_df.shape)

(260601, 38)
(260601, 1)


In [20]:
Y_train_df

damage_grade
building_id              
802906                  3
28830                   2
94947                   3
590882                  2
201944                  3
...                   ...
688636                  2
669485                  3
602512                  3
151409                  2
747594                  3

[260601 rows x 1 columns]

In [21]:
dummy_nonnumeric_cols = X_train_df.select_dtypes('O').columns.to_list()
dummy_nonnumeric_cols

['land_surface_condition',
 'foundation_type',
 'roof_type',
 'ground_floor_type',
 'other_floor_type',
 'position',
 'plan_configuration',
 'legal_ownership_status']

In [48]:
X_train_numerics = pd.concat([X_train_df.drop(columns=dummy_nonnumeric_cols),
           pd.get_dummies(X_train_df[dummy_nonnumeric_cols]),
          ], axis=1)

X_train_numerics
X_train_numerics.columns
X_train_numerics.shape

(260601, 68)

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [24]:
print(Y_train_df.head)

<bound method NDFrame.head of              damage_grade
building_id              
802906                  3
28830                   2
94947                   3
590882                  2
201944                  3
...                   ...
688636                  2
669485                  3
602512                  3
151409                  2
747594                  3

[260601 rows x 1 columns]>


In [0]:
X_train, X_valid, y_train, y_valid = train_test_split(X_train_numerics, Y_train_df, test_size=0.2)





In [26]:
X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((208480, 68), (52121, 68), (208480, 1), (52121, 1))

In [0]:
#model_eq = LogisticRegression(solver="liblinear")
model_eq = RandomForestClassifier(min_samples_leaf=10,  n_estimators=100, n_jobs=-1)





In [28]:
model_eq.fit(X_train, y_train["damage_grade"])

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=10, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [0]:
def compute_accuracy(model, X, y):
    y_pred = model.predict(X)
    print(confusion_matrix(y, y_pred))
    return accuracy_score(y, y_pred), f1_score(y, y_pred, average='micro')

In [42]:
print("EQ - Train", 
      compute_accuracy(model_eq, X_train, y_train["damage_grade"]))

[[  8376  11654    202]
 [  2516 107442   8518]
 [   224  33323  36225]]
EQ - Train (0.7292929777436684, 0.7292929777436684)


In [43]:
# Prepare test data
X_test_df = pd.read_csv("/content/drive/My Drive/DrivenData/EQ/EQ_Test_Values.csv",  index_col= 'building_id')

X_test_df.head

<bound method NDFrame.head of              geo_level_1_id  ...  has_secondary_use_other
building_id                  ...                         
300051                   17  ...                        0
99355                     6  ...                        0
890251                   22  ...                        0
745817                   26  ...                        0
421793                   17  ...                        0
...                     ...  ...                      ...
310028                    4  ...                        0
663567                   10  ...                        0
1049160                  22  ...                        0
442785                    6  ...                        0
501372                   26  ...                        0

[86868 rows x 38 columns]>

In [44]:
dummy_nonnumeric_cols_test = X_test_df.select_dtypes('O').columns.to_list()
dummy_nonnumeric_cols_test

['land_surface_condition',
 'foundation_type',
 'roof_type',
 'ground_floor_type',
 'other_floor_type',
 'position',
 'plan_configuration',
 'legal_ownership_status']

In [0]:
X_test_numerics = pd.concat([X_test_df.drop(columns=dummy_nonnumeric_cols_test),
           pd.get_dummies(X_test_df[dummy_nonnumeric_cols_test]),
          ], axis=1)


In [46]:
X_test_numerics.head()


geo_level_1_id  ...  legal_ownership_status_w
building_id                  ...                          
300051                   17  ...                         0
99355                     6  ...                         0
890251                   22  ...                         0
745817                   26  ...                         0
421793                   17  ...                         0

[5 rows x 68 columns]

In [0]:
predictions = model_eq.predict(X_test_numerics)

In [0]:
#submission

In [0]:
submission_01= pd.read_csv('/content/drive/My Drive/DrivenData/EQ/EQ_-_Submission_Format.csv', index_col='building_id')

In [0]:
my_submission_01 = pd.DataFrame(data=predictions,
                                columns =  submission_01.columns,
                                index = submission_01.index)

In [36]:
my_submission_01.head

<bound method NDFrame.head of              damage_grade
building_id              
300051                  3
99355                   2
890251                  2
745817                  1
421793                  3
...                   ...
310028                  2
663567                  2
1049160                 2
442785                  2
501372                  2

[86868 rows x 1 columns]>

In [0]:
my_submission_01.to_csv('/content/drive/My Drive/DrivenData/EQ/submission_003.csv')


In [0]:
#X_test_df.columns

array([0, 0, 0, ..., 0, 0, 1])

array([0.08967263, 0.04577297, 0.46643277, ..., 0.12036487, 0.06619229,
       0.54880332])

array([0.24109948, 0.04794604, 0.64113037, ..., 0.18405825, 0.39943752,
       0.48569194])

respondent_id  h1n1_vaccine  seasonal_vaccine
0          26707           0.5               0.7
1          26708           0.5               0.7
2          26709           0.5               0.7
3          26710           0.5               0.7
4          26711           0.5               0.7